import { INTEREST_LEVELS, RELATIONS } from '../config.js';
import { formatMoney } from '../utils/currency.js';
import { formatDate, daysUntil } from '../utils/dates.js';
import { escapeHtml, escapeAttr, safeHttpUrl } from '../utils/strings.js';
import { getIdeaDisplayState, isIdeaActive, isIdeaAbandoned, isIdeaOffered } from '../models/ideas.model.js';
export function empty(text='Aucune idée trouvée. Même CadeauScope ne peut pas retrouver une idée jamais notée.'){ return `<div class="card empty">${escapeHtml(text)}</div>`; }
export function ideaCard(idea, people=[], settings={}, {panic=false}={}){ const p=people.find(x=>x.id===idea.personId); const state=getIdeaDisplayState(idea); const url=safeHttpUrl(idea.link); const note=idea.note?String(idea.note).slice(0,140):''; return `<article class="card item"><div class="item-head"><div><h3 class="item-title">${escapeHtml(idea.title)}</h3><p class="muted">${escapeHtml(p?.name||'Personne disparue du radar')}${idea.estimatedPrice!=null?` · ${formatMoney(idea.estimatedPrice,settings)}`:''}</p></div>${state!=='active'?`<span class="badge ${state==='abandoned'?'warn':''}">${escapeHtml(state==='offered'?'Offert':'Abandonnée')}</span>`:''}</div>${note?`<p>${escapeHtml(note)}</p>`:''}<div class="actions">${panic&&url?`<button class="btn gold" data-panic-link="${escapeAttr(url)}">🔗 Ouvrir lien</button>`:''}${isIdeaActive(idea)?`<button class="btn ghost" data-idea-status="${escapeAttr(idea.id)}" data-next-status="offert">Offert</button>`:''}<button class="btn" data-idea-view="${escapeAttr(idea.id)}">Voir</button></div></article>`; }
export function personCard(person, ideas=[], history=[]){ const available=ideas.filter(i=>i.personId===person.id&&isIdeaActive(i)).length; const offered=history.filter(h=>h.personId===person.id).length; return `<article class="card item"><div class="item-head"><div><h3 class="item-title">${escapeHtml(person.name)}</h3><p class="muted">${escapeHtml(RELATIONS[person.relation]||'Autre')} · ${person.christmasEnabled?'Noël activé':'Noël en pause'}</p></div>${person.archived?'<span class="badge warn">Archivée</span>':''}</div><p>🎁 ${available} idées disponibles · 🧾 ${offered} cadeaux offerts</p><div class="actions"><button class="btn ghost" data-route="quick" data-person="${escapeAttr(person.id)}">Ajouter idée</button><button class="btn" data-route="person" data-id="${escapeAttr(person.id)}">Voir</button></div></article>`; }
export function occasionCard(o, ideas=[], people=[]){ const personIds=new Set(o.personIds||[]); const available=ideas.filter(i=>personIds.has(i.personId)&&isIdeaActive(i)).length; const d=daysUntil(o.date); const names=people.length?(o.personIds||[]).map(id=>people.find(p=>p.id===id)?.name).filter(Boolean).slice(0,3).join(', '):''; return `<article class="card item"><div class="item-head"><div><h3 class="item-title">${o.type==='christmas'?'🎄':'📅'} ${escapeHtml(o.name)}</h3><p class="muted">${formatDate(o.date)} · ${d>=0?`J-${d}`:'passée'}${names?` · ${escapeHtml(names)}`:''}</p></div><span class="badge">${o.personIds?.length||0} pers.</span></div><p>${available} idée(s) disponible(s) pour les personnes concernées${o.totalBudget?` · budget ${escapeHtml(o.totalBudget)} €`:''}</p><div class="actions"><button class="btn" data-route="occasion" data-id="${escapeAttr(o.id)}">Voir</button><button class="btn ghost" data-route="panic" data-occasion="${escapeAttr(o.id)}">Mode Panique</button></div></article>`; }
export { INTEREST_LEVELS, isIdeaActive, isIdeaOffered, isIdeaAbandoned };
