import { STATUSES, INTEREST_LEVELS, RELATIONS } from '../config.js';
import { formatMoney } from '../utils/currency.js';
import { formatDate, daysUntil } from '../utils/dates.js';
import { escapeHtml } from '../utils/strings.js';
export function empty(text='Aucune idée trouvée. Même CadeauScope ne peut pas retrouver une idée jamais notée.'){ return `<div class="card empty">${text}</div>`; }
export function ideaCard(idea, people=[], settings={}, {panic=false}={}){ const p=people.find(x=>x.id===idea.personId); const next=nextAction(idea.status); return `<article class="card item"><div class="item-head"><div><h3 class="item-title">${escapeHtml(idea.title)}</h3><p class="muted">${escapeHtml(p?.name||'Personne disparue du radar')} · ${formatMoney(idea.estimatedPrice,settings)} · ${INTEREST_LEVELS[idea.interestLevel]}</p></div><span class="badge">${STATUSES[idea.status]}</span></div>${idea.note?`<p>${escapeHtml(idea.note)}</p>`:''}<div class="actions">${panic&&idea.link?`<a class="btn gold" href="${escapeHtml(idea.link)}" target="_blank" rel="noreferrer">🔗 Ouvrir</a>`:''}${next?`<button class="btn ghost" data-status="${idea.id}" data-next="${next.status}">${next.label}</button>`:''}<button class="btn" data-route="idea" data-id="${idea.id}">Voir</button></div></article>`; }
export function personCard(person, ideas=[], history=[]){ const available=ideas.filter(i=>i.personId===person.id&&!['offert','abandonne'].includes(i.status)).length; const offered=history.filter(h=>h.personId===person.id).length; return `<article class="card item"><div class="item-head"><div><h3 class="item-title">${escapeHtml(person.name)}</h3><p class="muted">${RELATIONS[person.relation]||'Autre'} · ${person.christmasEnabled?'Noël activé':'Noël en pause'}</p></div>${person.archived?'<span class="badge warn">Archivée</span>':''}</div><p>🎁 ${available} idées disponibles · 🧾 ${offered} cadeaux offerts</p><div class="actions"><button class="btn ghost" data-route="quick" data-person="${person.id}">Ajouter idée</button><button class="btn" data-route="person" data-id="${person.id}">Voir</button></div></article>`; }
export function occasionCard(o, ideas=[]){ const linked=ideas.filter(i=>i.occasionId===o.id || (o.type==='christmas'&&i.occasionMode==='christmas')).length; const d=daysUntil(o.date); return `<article class="card item"><div class="item-head"><div><h3 class="item-title">${o.type==='christmas'?'🎄':'📅'} ${escapeHtml(o.name)}</h3><p class="muted">${formatDate(o.date)} · ${d>=0?`J-${d}`:'passée'}</p></div><span class="badge">${o.personIds?.length||0} pers.</span></div><p>${linked} idée(s) liées${o.totalBudget?` · budget ${o.totalBudget} €`:''}</p><div class="actions"><button class="btn" data-route="occasion" data-id="${o.id}">Voir</button><button class="btn ghost" data-route="panic" data-occasion="${o.id}">Mode Panique</button></div></article>`; }
function nextAction(status){ return ({idee:{status:'a_acheter',label:'À acheter'},a_acheter:{status:'achete',label:'Acheté'},achete:{status:'emballe',label:'Emballé'},emballe:{status:'offert',label:'Offert'}})[status]; }
