import { setMain, serializeForm } from '../ui/dom.js';
import { getIdea, duplicateIdea, abandonIdea, deleteIdea, saveIdea, requestIdeaStatusChange } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { listCategories } from '../services/categories.service.js';
import { getSettings } from '../services/settings.service.js';
import { getPhoto, savePhoto } from '../services/photos.service.js';
import { INTEREST_LEVELS } from '../config.js';
import { peopleOptions, categoryOptions, options } from '../ui/forms.js';
import { formatMoney } from '../utils/currency.js';
import { escapeHtml, escapeAttr, safeHttpUrl } from '../utils/strings.js';
import { navigate } from '../router.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog, modal, closeModal } from '../ui/modals.js';
import { getIdeaDisplayState, isIdeaActive } from '../models/ideas.model.js';
export async function renderIdeaDetail({id}){ const [idea,people,cats,settings]=await Promise.all([getIdea(id),listPeople(true),listCategories(),getSettings()]); if(!idea){setMain('<div class="card empty">Idée introuvable. Le radar a perdu le paquet.</div>');return;} const p=people.find(x=>x.id===idea.personId), url=safeHttpUrl(idea.link); const state=getIdeaDisplayState(idea); setMain(`<section class="screen stack"><button class="btn" data-back>← Retour</button><article class="card"><h1>${escapeHtml(idea.title)}</h1><div class="details"><div class="detail-row"><b>Personne</b><span>${escapeHtml(p?.name||'')}</span></div><div class="detail-row"><b>Prix approx.</b><span>${formatMoney(idea.estimatedPrice,settings)}</span></div><div class="detail-row"><b>État</b><span>${escapeHtml(state==='active'?'Idée':state==='offered'?'Offert':'Abandonnée')}</span></div></div>${idea.note?`<p>${escapeHtml(idea.note)}</p>`:''}${url?`<p><a href="${escapeAttr(url)}" target="_blank" rel="noreferrer">🔗 Ouvrir le lien</a></p>`:''}${idea.description?`<details><summary>Détails optionnels</summary><p>${escapeHtml(idea.description)}</p></details>`:''}<div class="photo-preview" id="photo-preview">${idea.photoId?'Chargement de la photo locale…':'Aucune photo'}</div></article><div class="card actions">${isIdeaActive(idea)?'<button class="btn primary" data-offered>Marquer comme offert</button>':''}<button class="btn ghost" data-edit>Modifier</button><details class="actions-menu"><summary class="btn">…</summary><div class="stack"><button class="btn ghost" data-dup>Dupliquer</button><button class="btn" data-abandon>Ne plus proposer cette idée</button><button class="btn danger" data-delete>Supprimer</button></div></details></div></section>`); await renderPhoto(idea.photoId); bind(idea,people,cats,settings); }
async function renderPhoto(photoId){ if(!photoId) return; const box=document.querySelector('#photo-preview'); const photo=await getPhoto(photoId); if(!box) return; if(!photo?.blob){ box.textContent='Photo introuvable'; return; } const url=URL.createObjectURL(photo.blob); box.innerHTML=''; const img=document.createElement('img'); img.alt='Photo locale de l’idée'; img.style.maxWidth='100%'; img.style.borderRadius='16px'; img.onload=()=>URL.revokeObjectURL(url); img.src=url; box.appendChild(img); }
function editFields(idea,people,cats,settings){ return `<form id="edit-idea" class="form-card"><div class="field"><label>Idée cadeau *</label><input name="title" value="${escapeAttr(idea.title)}" required></div><div class="field"><label>Pour qui ? *</label><select name="personId" required>${peopleOptions(people,idea.personId)}</select></div><div class="field"><label>Prix approx.</label><input name="estimatedPrice" type="number" min="0" step="0.01" placeholder="ex : 30" value="${escapeAttr(idea.estimatedPrice ?? '')}"></div><div class="field"><label>Lien</label><input name="link" value="${escapeAttr(idea.link)}" placeholder="https://..."></div><div class="field"><label>Note</label><textarea name="note">${escapeHtml(idea.note)}</textarea></div><details><summary>Détails optionnels</summary><div class="stack"><div class="field"><label>Description</label><textarea name="description">${escapeHtml(idea.description)}</textarea></div><div class="field"><label>Catégorie</label><select name="categoryId">${categoryOptions(cats,idea.categoryId)}</select></div><div class="field"><label>Niveau d’intérêt</label><select name="interestLevel">${options(INTEREST_LEVELS,idea.interestLevel||settings.defaultInterestLevel)}</select></div><div class="field"><label>Remplacer la photo</label><input name="photo" type="file" accept="image/*"><small class="muted">L’ancienne photo est conservée si aucun fichier n’est choisi.</small></div></div></details><button class="btn primary">Enregistrer</button></form>`; }
function bind(idea,people,cats,settings){ document.querySelector('[data-back]').onclick=()=>navigate('ideas'); document.querySelector('[data-offered]')?.addEventListener('click',async()=>{ const changed=await requestIdeaStatusChange(idea.id,'offert'); if(changed){toast('Idée marquée comme offerte.');navigate('idea',{id:idea.id});} }); document.querySelector('[data-dup]').onclick=async()=>{const copy=await duplicateIdea(idea.id);toast('Idée dupliquée. Clone sans historique, comme demandé.');navigate('idea',{id:copy.id});}; document.querySelector('[data-abandon]').onclick=async()=>{await abandonIdea(idea.id);toast('Cette idée ne sera plus proposée.');navigate('ideas');}; document.querySelector('[data-delete]').onclick=async()=>{if(await confirmDialog({message:'Supprimer définitivement cette idée ?',danger:true,confirmText:'Supprimer'})){await deleteIdea(idea.id);navigate('ideas');}}; document.querySelector('[data-edit]').onclick=()=>{ modal({title:'Modifier l’idée',body:editFields(idea,people,cats,settings)}); document.querySelector('#edit-idea').onsubmit=async e=>{ e.preventDefault(); try{ const form=e.target; const file=form.photo.files[0]; const data=serializeForm(form); let saved=await saveIdea({...idea,...data,occasionMode:idea.occasionMode||'none',occasionId:idea.occasionId||''}); if(file){ const photo=await savePhoto({ownerType:'idea',ownerId:idea.id,blob:file,mimeType:file.type}); saved=await saveIdea({...saved,photoId:photo.id}); } toast('Idée mise à jour.'); closeModal(); navigate('idea',{id:idea.id}); }catch(err){ toast(Object.values(err.errors||{})[0]||err.message); } }; }; }
