import { setMain } from '../ui/dom.js';
import { getIdea, duplicateIdea, abandonIdea, deleteIdea, updateStatus } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { listCategories } from '../services/categories.service.js';
import { getSettings } from '../services/settings.service.js';
import { historyFromIdea } from '../services/history.service.js';
import { getOccasion } from '../services/occasions.service.js';
import { STATUSES, INTEREST_LEVELS, STATUS_FLOW } from '../config.js';
import { formatMoney } from '../utils/currency.js';
import { escapeHtml } from '../utils/strings.js';
import { navigate } from '../router.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog, modal } from '../ui/modals.js';
export async function renderIdeaDetail({id}){ const [idea,people,cats,settings]=await Promise.all([getIdea(id),listPeople(true),listCategories(),getSettings()]); if(!idea){setMain('<div class="card empty">Idée introuvable. Le radar a perdu le paquet.</div>');return;} const p=people.find(x=>x.id===idea.personId), c=cats.find(x=>x.id===idea.categoryId); setMain(`<section class="screen stack"><button class="btn" data-back>← Retour</button><article class="card"><h1>${escapeHtml(idea.title)}</h1><div class="details"><div class="detail-row"><b>Personne</b><span>${escapeHtml(p?.name||'')}</span></div><div class="detail-row"><b>Prix estimé</b><span>${formatMoney(idea.estimatedPrice,settings)}</span></div><div class="detail-row"><b>Budget approx.</b><span>${escapeHtml(idea.priceText||'')}</span></div><div class="detail-row"><b>Niveau</b><span>${INTEREST_LEVELS[idea.interestLevel]}</span></div><div class="detail-row"><b>Statut</b><span>${STATUSES[idea.status]}</span></div><div class="detail-row"><b>Catégorie</b><span>${escapeHtml(c?.name||'Autre')}</span></div></div><p>${escapeHtml(idea.note||'')}</p><p>${escapeHtml(idea.description||'')}</p>${idea.link?`<p><a href="${escapeHtml(idea.link)}" target="_blank" rel="noreferrer">🔗 Ouvrir le lien</a></p>`:''}<div class="photo-preview">${idea.photoId?'Photo locale enregistrée':'Aucune photo'}</div><div class="progress">${STATUS_FLOW.map(s=>`<span class="step ${STATUS_FLOW.indexOf(s)<=STATUS_FLOW.indexOf(idea.status)?'done':''}">${STATUSES[s]}</span>`).join('')}</div></article><div class="card actions"><button class="btn ghost" data-dup>Dupliquer</button><button class="btn" data-next>Changer statut</button><button class="btn danger" data-abandon>Abandonner</button><button class="btn danger" data-delete>Supprimer</button></div></section>`); document.querySelector('[data-back]').onclick=()=>navigate('ideas'); document.querySelector('[data-dup]').onclick=async()=>{const copy=await duplicateIdea(id);toast('Idée dupliquée. Clone sans historique, comme demandé.');navigate('idea',{id:copy.id});}; document.querySelector('[data-abandon]').onclick=async()=>{await abandonIdea(id);toast('Idée abandonnée, mais pas oubliée.');navigate('ideas');}; document.querySelector('[data-delete]').onclick=async()=>{if(await confirmDialog({message:'Supprimer définitivement cette idée ?',danger:true,confirmText:'Supprimer'})){await deleteIdea(id);navigate('ideas');}}; document.querySelector('[data-next]').onclick=async()=>advance(idea); }
async function advance(idea){ const idx=STATUS_FLOW.indexOf(idea.status); const next=STATUS_FLOW[Math.min(idx+1,STATUS_FLOW.length-1)]; if(next==='offert'){ modal({title:'Ajouter ce cadeau à l’historique ?',body:'<p>Le paquet est parti. On garde une trace de la réaction ?</p>',actions:'<button class="btn primary" data-yes>Oui, ajouter</button><button class="btn ghost" data-no>Non, juste marquer offert</button><button class="btn" data-cancel>Annuler</button>'}); document.querySelector('[data-yes]').onclick=async()=>{await updateStatus(idea.id,'offert'); await historyFromIdea(idea, idea.occasionId?await getOccasion(idea.occasionId):null); toast('Historique ajouté. Le coffre se souvient.'); navigate('idea',{id:idea.id});}; document.querySelector('[data-no]').onclick=async()=>{await updateStatus(idea.id,'offert');navigate('idea',{id:idea.id});}; } else { await updateStatus(idea.id,next); toast('Statut mis à jour.'); navigate('idea',{id:idea.id}); } }
