import { setMain } from '../ui/dom.js';
import { listIdeas } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { getSettings } from '../services/settings.service.js';
import { ideaCard, empty } from '../ui/render.js';
import { includesText, escapeHtml, escapeAttr } from '../utils/strings.js';
import { bindIdeaCardActions } from '../ui/idea-card-actions.js';
import { isIdeaActive, isIdeaOffered, isIdeaAbandoned } from '../models/ideas.model.js';
export async function renderIdeas(){ const [ideas,people,settings]=await Promise.all([listIdeas(),listPeople(true),getSettings()]); setMain(`<section class="screen stack"><div class="screen-header"><div><h1 class="screen-title">💡 Idées</h1><p class="screen-subtitle">Des idées disponibles, rangées par personne.</p></div></div><input id="search" class="field-input" placeholder="Rechercher"><div class="chip-row" id="filters">${['Toutes','Disponibles','Offertes'].map((f,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><details class="card"><summary>Filtre avancé</summary><div class="grid"><select id="advanced"><option value="">—</option><option value="abandoned">Abandonnées</option></select><select id="person"><option value="">Personne</option>${people.map(p=>`<option value="${escapeAttr(p.id)}">${escapeHtml(p.name)}</option>`).join('')}</select><input id="budget" type="number" placeholder="Budget max"><select id="sort"><option value="recent">Plus récent</option><option value="priceAsc">Prix croissant</option><option value="priceDesc">Prix décroissant</option><option value="best">Meilleures idées</option></select></div></details><div id="ideas-list" class="list"></div></section>`); const render=()=>{ let filter=document.querySelector('.chip.active').dataset.filter; let q=document.querySelector('#search').value; let data=[...ideas]; const advanced=document.querySelector('#advanced').value; if(advanced==='abandoned') data=data.filter(isIdeaAbandoned); else if(filter==='Offertes') data=data.filter(isIdeaOffered); else data=data.filter(isIdeaActive); const pid=document.querySelector('#person').value; if(pid)data=data.filter(i=>i.personId===pid); const b=Number(document.querySelector('#budget').value); if(b>0)data=data.filter(i=>i.estimatedPrice==null||i.estimatedPrice<=b); if(q)data=data.filter(i=>includesText(`${i.title} ${i.note} ${i.description} ${people.find(p=>p.id===i.personId)?.name}`,q)); const sort=document.querySelector('#sort').value; data.sort((a,b)=>sort==='priceAsc'?(a.estimatedPrice??999999)-(b.estimatedPrice??999999):sort==='priceDesc'?(b.estimatedPrice??-1)-(a.estimatedPrice??-1):sort==='best'?(b.interestLevel||0)-(a.interestLevel||0):new Date(b.createdAt)-new Date(a.createdAt)); document.querySelector('#ideas-list').innerHTML=data.length?data.map(i=>ideaCard(i,people,settings)).join(''):empty(); bindList(); }; document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');document.querySelector('#advanced').value='';render();}); ['search','person','budget','sort','advanced'].forEach(id=>document.querySelector('#'+id).oninput=render); render(); }
function bindList(){ bindIdeaCardActions(document.querySelector('#ideas-list'),{onStatusChanged:renderIdeas}); }
