import { setMain, serializeForm } from '../ui/dom.js';
import { getIdea, duplicateIdea, abandonIdea, deleteIdea, saveIdea, requestIdeaStatusChange } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { listCategories } from '../services/categories.service.js';
import { listOccasions } from '../services/occasions.service.js';
import { getSettings } from '../services/settings.service.js';
import { getPhoto, savePhoto } from '../services/photos.service.js';
import { STATUSES, INTEREST_LEVELS, STATUS_FLOW } from '../config.js';
import { options, peopleOptions, categoryOptions } from '../ui/forms.js';
import { formatMoney } from '../utils/currency.js';
import { escapeHtml, escapeAttr, safeHttpUrl } from '../utils/strings.js';
import { navigate } from '../router.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog, modal, closeModal } from '../ui/modals.js';
export async function renderIdeaDetail({id}){ const [idea,people,cats,settings,occasions]=await Promise.all([getIdea(id),listPeople(true),listCategories(),getSettings(),listOccasions('toutes')]); if(!idea){setMain('<div class="card empty">Idée introuvable. Le radar a perdu le paquet.</div>');return;} const p=people.find(x=>x.id===idea.personId), c=cats.find(x=>x.id===idea.categoryId), url=safeHttpUrl(idea.link); const occasion=occasions.find(o=>o.id===idea.occasionId); setMain(`<section class="screen stack"><button class="btn" data-back>← Retour</button><article class="card"><h1>${escapeHtml(idea.title)}</h1><div class="details"><div class="detail-row"><b>Personne</b><span>${escapeHtml(p?.name||'')}</span></div><div class="detail-row"><b>Prix estimé</b><span>${formatMoney(idea.estimatedPrice,settings)}</span></div><div class="detail-row"><b>Budget approx.</b><span>${escapeHtml(idea.priceText||'')}</span></div><div class="detail-row"><b>Niveau</b><span>${escapeHtml(INTEREST_LEVELS[idea.interestLevel]||'')}</span></div><div class="detail-row"><b>Statut</b><span>${escapeHtml(STATUSES[idea.status]||idea.status)}</span></div><div class="detail-row"><b>Catégorie</b><span>${escapeHtml(c?.name||'Autre')}</span></div><div class="detail-row"><b>Occasion</b><span>${escapeHtml(occasion?.name||idea.occasionMode||'Aucune')}</span></div></div><p>${escapeHtml(idea.note||'')}</p><p>${escapeHtml(idea.description||'')}</p>${url?`<p><a href="${escapeAttr(url)}" target="_blank" rel="noreferrer">🔗 Ouvrir le lien</a></p>`:''}<div class="photo-preview" id="photo-preview">${idea.photoId?'Chargement de la photo locale…':'Aucune photo'}</div><div class="progress">${STATUS_FLOW.map(s=>`<span class="step ${STATUS_FLOW.indexOf(s)<=STATUS_FLOW.indexOf(idea.status)?'done':''}">${escapeHtml(STATUSES[s])}</span>`).join('')}</div></article><div class="card actions"><button class="btn primary" data-edit>Modifier</button><button class="btn ghost" data-dup>Dupliquer</button><button class="btn" data-next>Changer statut</button><button class="btn danger" data-abandon>Abandonner</button><button class="btn danger" data-delete>Supprimer</button></div></section>`); await renderPhoto(idea.photoId); bind(idea,people,cats,settings,occasions); }
async function renderPhoto(photoId){ if(!photoId) return; const box=document.querySelector('#photo-preview'); const photo=await getPhoto(photoId); if(!box) return; if(!photo?.blob){ box.textContent='Photo introuvable'; return; } const url=URL.createObjectURL(photo.blob); box.innerHTML=''; const img=document.createElement('img'); img.alt='Photo locale de l’idée'; img.style.maxWidth='100%'; img.style.borderRadius='16px'; img.onload=()=>URL.revokeObjectURL(url); img.src=url; box.appendChild(img); }
function editFields(idea,people,cats,settings,occasions){ const manual=occasions.filter(o=>o.source!=='auto'); return `<form id="edit-idea" class="form-card"><div class="field"><label>Titre *</label><input name="title" value="${escapeAttr(idea.title)}" required></div><div class="field"><label>Personne *</label><select name="personId" required>${peopleOptions(people,idea.personId)}</select></div><div class="field"><label>Statut</label><select name="status">${options(STATUSES,idea.status)}</select></div><div class="two grid"><div class="field"><label>Prix estimé</label><input name="estimatedPrice" type="number" min="0" step="0.01" value="${escapeAttr(idea.estimatedPrice ?? '')}"></div><div class="field"><label>Budget approximatif</label><input name="priceText" value="${escapeAttr(idea.priceText)}"></div></div><div class="field"><label>Niveau d’intérêt</label><select name="interestLevel">${options(INTEREST_LEVELS,idea.interestLevel||settings.defaultInterestLevel)}</select></div><div class="field"><label>Catégorie</label><select name="categoryId">${categoryOptions(cats,idea.categoryId)}</select></div><div class="field"><label>Occasion</label><select name="occasionMode" id="edit-occasion-mode"><option value="none" ${idea.occasionMode==='none'?'selected':''}>Aucune</option><option value="birthday" ${idea.occasionMode==='birthday'?'selected':''}>Anniversaire</option><option value="christmas" ${idea.occasionMode==='christmas'?'selected':''}>Noël</option><option value="manual" ${idea.occasionMode==='manual'?'selected':''}>Manuelle</option></select></div><div class="field" id="edit-manual-occasion"><label>Occasion manuelle</label><select name="occasionId"><option value="">Choisir</option>${manual.map(o=>`<option value="${escapeAttr(o.id)}" ${o.id===idea.occasionId?'selected':''}>${escapeHtml(o.name)}</option>`).join('')}</select></div><div class="field"><label>Lien</label><input name="link" value="${escapeAttr(idea.link)}" placeholder="https://..."></div><div class="field"><label>Note courte</label><textarea name="note">${escapeHtml(idea.note)}</textarea></div><div class="field"><label>Description</label><textarea name="description">${escapeHtml(idea.description)}</textarea></div><div class="field"><label>Remplacer la photo</label><input name="photo" type="file" accept="image/*"><small class="muted">L’ancienne photo est conservée si aucun fichier n’est choisi.</small></div><button class="btn primary">Enregistrer</button></form>`; }
function toggleEditOccasion(){ const manual=document.querySelector('#edit-occasion-mode')?.value==='manual'; const field=document.querySelector('#edit-manual-occasion'); if(field) field.hidden=!manual; if(!manual){ const select=field?.querySelector('select'); if(select) select.value=''; } }
function bind(idea,people,cats,settings,occasions){ document.querySelector('[data-back]').onclick=()=>navigate('ideas'); document.querySelector('[data-dup]').onclick=async()=>{const copy=await duplicateIdea(idea.id);toast('Idée dupliquée. Clone sans historique, comme demandé.');navigate('idea',{id:copy.id});}; document.querySelector('[data-abandon]').onclick=async()=>{await abandonIdea(idea.id);toast('Idée abandonnée, mais pas oubliée.');navigate('ideas');}; document.querySelector('[data-delete]').onclick=async()=>{if(await confirmDialog({message:'Supprimer définitivement cette idée ?',danger:true,confirmText:'Supprimer'})){await deleteIdea(idea.id);navigate('ideas');}}; document.querySelector('[data-next]').onclick=async()=>{ const idx=STATUS_FLOW.indexOf(idea.status); const next=STATUS_FLOW[Math.min(idx+1,STATUS_FLOW.length-1)]; const changed=await requestIdeaStatusChange(idea.id,next); if(changed){toast('Statut mis à jour.');navigate('idea',{id:idea.id});} }; document.querySelector('[data-edit]').onclick=()=>{ modal({title:'Modifier l’idée',body:editFields(idea,people,cats,settings,occasions)}); document.querySelector('#edit-occasion-mode').onchange=toggleEditOccasion; toggleEditOccasion(); document.querySelector('#edit-idea').onsubmit=async e=>{ e.preventDefault(); try{ const form=e.target; const file=form.photo.files[0]; const data=serializeForm(form); if(data.occasionMode!=='manual') data.occasionId=''; const requested=data.status; const baseStatus=requested==='offert'&&idea.status!=='offert'?idea.status:requested; let saved=await saveIdea({...idea,...data,status:baseStatus}); if(file){ const photo=await savePhoto({ownerType:'idea',ownerId:idea.id,blob:file,mimeType:file.type}); saved=await saveIdea({...saved,photoId:photo.id}); } if(requested==='offert'&&idea.status!=='offert') await requestIdeaStatusChange(idea.id,'offert'); toast('Idée mise à jour.'); closeModal(); navigate('idea',{id:idea.id}); }catch(err){ toast(Object.values(err.errors||{})[0]||err.message); } }; }; }
