import { setMain, serializeForm } from '../ui/dom.js';
import { getOccasion, saveOccasion, closeOccasion, deleteOccasion, updateEventPeople } from '../services/occasions.service.js';
import { listIdeas } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { spentForOccasion } from '../services/budget.service.js';
import { ideaCard, empty } from '../ui/render.js';
import { bindIdeaCardActions } from '../ui/idea-card-actions.js';
import { formatDate, daysUntil } from '../utils/dates.js';
import { escapeHtml, escapeAttr } from '../utils/strings.js';
import { navigate } from '../router.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog, modal, closeModal } from '../ui/modals.js';
import { isIdeaActive } from '../models/ideas.model.js';
export async function renderOccasionDetail({id}){ const isNew=id==='new'; const [occasion,people,allIdeas]=await Promise.all([isNew?null:getOccasion(id),listPeople(true),listIdeas()]); if(isNew){ setMain(`<section class="screen stack"><h1>Créer un événement</h1><form id="occasion-form" class="card form-card">${fields({},people)}<button class="btn primary">Enregistrer</button></form></section>`); document.querySelector('#occasion-form').onsubmit=async e=>{e.preventDefault();try{const o=await saveOccasion({...serializeForm(e.target),personIds:checkedPeople(e.target)});toast('Événement créé.');navigate('occasion',{id:o.id});}catch(err){toast(Object.values(err.errors||{})[0]||err.message)}}; return; }
 if(!occasion){ setMain(empty('Événement introuvable.')); return; }
 const activePeople=people.filter(p=>!p.archived); const concernedIds=(occasion.personIds||[]).filter(pid=>activePeople.some(p=>p.id===pid)); const concerned=new Set(concernedIds); const available=allIdeas.filter(i=>concerned.has(i.personId)&&isIdeaActive(i)); const spent=spentForOccasion(allIdeas.filter(i=>concerned.has(i.personId))); const names=concernedIds.map(pid=>activePeople.find(p=>p.id===pid)?.name).filter(Boolean); const grouped=concernedIds.map(pid=>{ const person=activePeople.find(p=>p.id===pid); const ideas=available.filter(i=>i.personId===pid); return `<section class="stack"><h3>${escapeHtml(person?.name||'Personne')}</h3>${ideas.length?ideas.map(i=>ideaCard(i,activePeople,{})).join(''):empty('Aucune idée disponible pour cette personne.')}</section>`; }).join(''); const d=daysUntil(occasion.date);
 setMain(`<section class="screen stack"><button class="btn" data-back>← Retour</button><article class="card"><h1>${escapeHtml(occasion.name)}</h1><p>${formatDate(occasion.date)} · ${d>=0?`Dans ${d} jour(s)`:'date passée'}</p><p class="muted">Cet événement est lié à des personnes, pas directement aux idées.</p><div class="actions"><button class="btn primary" data-route="panic" data-occasion="${escapeAttr(occasion.id)}">Mode Panique</button><button class="btn ghost" data-route="quick" data-person="${escapeAttr(concernedIds.length===1?concernedIds[0]:'')}">Ajouter une idée</button><button class="btn" data-edit-people>Modifier les personnes</button>${occasion.source==='manual'?'<button class="btn" data-edit>Modifier</button>':''}${d<0?'<button class="btn" data-close>Clôturer</button>':''}<button class="btn danger" data-delete>${occasion.source==='manual'?'Supprimer':'Masquer'}</button></div></article><div class="card details"><div class="detail-row"><b>Budget global</b><span>${spent} / ${occasion.totalBudget||'—'} €</span></div><div class="detail-row"><b>Personnes liées</b><span>${names.map(escapeHtml).join(', ')||'—'}</span></div>${occasion.notes?`<div class="detail-row"><b>Note</b><span>${escapeHtml(occasion.notes)}</span></div>`:''}</div><h2>Personnes liées</h2><div class="card">${names.length?`<p>${names.map(escapeHtml).join(', ')}</p>`:'<p class="muted">Aucune personne liée. Cet événement ne remontera pas sur l’accueil.</p>'}<button class="btn ghost" data-edit-people>Modifier les personnes</button></div><h2>Idées disponibles</h2>${grouped||empty('Lie au moins une personne pour voir ses idées disponibles.')}</section>`);
 bindIdeaCardActions(document,{onStatusChanged:()=>renderOccasionDetail({id:occasion.id})}); document.querySelector('[data-back]').onclick=()=>navigate('occasions'); document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route,{occasionId:b.dataset.occasion,personId:b.dataset.person})); document.querySelectorAll('[data-edit-people]').forEach(b=>b.onclick=()=>openPeopleModal(occasion,people)); document.querySelector('[data-edit]')?.addEventListener('click',()=>modal({title:'Modifier événement',body:`<form id="edit-event" class="form-card">${fields(occasion,people)}<button class="btn primary">Enregistrer</button></form>`})); document.querySelector('[data-close]')?.addEventListener('click',async()=>{if(await confirmDialog({message:'Clôturer cet événement ?',confirmText:'Clôturer'})){await closeOccasion(occasion.id);navigate('occasion',{id:occasion.id});}}); document.querySelector('[data-delete]')?.addEventListener('click',async()=>{if(await confirmDialog({message:occasion.source==='manual'?'Supprimer cet événement personnalisé ? Les idées restent attachées à leurs personnes.':'Masquer cet événement classique ?',danger:true,confirmText:occasion.source==='manual'?'Supprimer':'Masquer'})){await deleteOccasion(occasion.id);navigate('occasions');}}); document.addEventListener('submit',async e=>{ if(e.target.id==='edit-event'){ e.preventDefault(); await saveOccasion({...occasion,...serializeForm(e.target),personIds:checkedPeople(e.target)}); toast('Événement mis à jour.'); closeModal(); navigate('occasion',{id:occasion.id}); } },{once:true}); }
function checkedPeople(form){ return [...form.querySelectorAll('[name="personIds"]:checked')].map(input=>input.value); }
function peopleChecks(people, selected=[]){ const ids=new Set(selected); return `<div class="stack">${people.filter(p=>!p.archived).map(p=>`<label><input type="checkbox" name="personIds" value="${escapeAttr(p.id)}" ${ids.has(p.id)?'checked':''}> ${escapeHtml(p.name)}</label>`).join('')}</div>`; }
function fields(o,people){ return `<div class="field"><label>Nom *</label><input name="name" value="${escapeAttr(o.name||'')}" required></div><div class="field"><label>Date *</label><input type="date" name="date" value="${escapeAttr(o.date||'')}" required></div><div class="field"><label>Personnes concernées</label>${peopleChecks(people,o.personIds||[])}</div><input name="totalBudget" type="number" min="0" step="0.01" placeholder="Budget global optionnel" value="${escapeAttr(o.totalBudget ?? '')}"><textarea name="notes" placeholder="Note optionnelle">${escapeHtml(o.notes||'')}</textarea>`; }
function openPeopleModal(occasion,people){ modal({title:'Modifier les personnes',body:`<form id="event-people" class="form-card"><p class="muted">Coche les personnes concernées par cet événement.</p>${peopleChecks(people,occasion.personIds||[])}<button class="btn primary">Enregistrer</button></form>`}); document.querySelector('#event-people').onsubmit=async e=>{ e.preventDefault(); await updateEventPeople(occasion.id,checkedPeople(e.target)); toast('Personnes liées mises à jour.'); closeModal(); navigate('occasion',{id:occasion.id}); }; }
