import { setMain, serializeForm } from '../ui/dom.js';
import { getOccasion, saveOccasion, closeOccasion, deleteOccasion } from '../services/occasions.service.js';
import { listIdeas } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { spentForOccasion } from '../services/budget.service.js';
import { OCCASION_TYPES, OCCASION_STATUS } from '../config.js';
import { options, peopleOptions } from '../ui/forms.js';
import { ideaCard } from '../ui/render.js';
import { formatDate, daysUntil } from '../utils/dates.js';
import { escapeHtml } from '../utils/strings.js';
import { navigate } from '../router.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog } from '../ui/modals.js';
export async function renderOccasionDetail({id}){ const isNew=id==='new'; const [occasion,people,allIdeas]=await Promise.all([isNew?null:getOccasion(id),listPeople(),listIdeas()]); if(isNew){ setMain(`<section class="screen stack"><h1>Créer une occasion</h1><form id="occasion-form" class="card form-card">${fields({},people)}<button class="btn primary">Enregistrer</button></form></section>`); document.querySelector('#occasion-form').onsubmit=async e=>{e.preventDefault();try{const o=await saveOccasion({...serializeForm(e.target),personIds:[...e.target.personIds.selectedOptions].map(o=>o.value)});toast('Occasion créée. Le calendrier tremble.');navigate('occasion',{id:o.id});}catch(err){toast(Object.values(err.errors||{})[0]||err.message)}}; return; } const linked=allIdeas.filter(i=>i.occasionId===occasion.id || (occasion.type==='christmas'&&i.occasionMode==='christmas')); const spent=spentForOccasion(linked); setMain(`<section class="screen stack"><button class="btn" data-back>← Retour</button><article class="card"><h1>${escapeHtml(occasion.name)}</h1><p>${formatDate(occasion.date)} · ${daysUntil(occasion.date)>=0?`J-${daysUntil(occasion.date)}`:'date passée'}</p><div class="actions"><button class="btn primary" data-route="panic" data-occasion="${occasion.id}">Mode Panique</button><button class="btn ghost" data-route="quick">Ajouter idée</button>${daysUntil(occasion.date)<0?'<button class="btn" data-close>Clôturer</button>':''}${occasion.source!=='auto'?'<button class="btn danger" data-delete>Supprimer</button>':''}</div></article><div class="card details"><div class="detail-row"><b>Budget global</b><span>${spent} / ${occasion.totalBudget||'—'} €</span></div><div class="detail-row"><b>Budget par personne</b><span>${Object.keys(occasion.personBudgets||{}).length?'défini':'—'}</span></div><div class="detail-row"><b>Personnes</b><span>${occasion.personIds?.length||0}</span></div><div class="detail-row"><b>Statut</b><span>${OCCASION_STATUS[occasion.status]||occasion.status}</span></div></div><h2>Idées liées</h2>${linked.map(i=>ideaCard(i,people,{})).join('')||'<div class="card empty">Aucune idée liée. Le radar attend une piste.</div>'}</section>`); document.querySelector('[data-back]').onclick=()=>navigate('occasions'); document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route,{occasionId:b.dataset.occasion})); document.querySelector('[data-close]')?.addEventListener('click',async()=>{if(await confirmDialog({message:'Clôturer cette occasion ?',confirmText:'Clôturer'})){await closeOccasion(occasion.id);navigate('occasion',{id:occasion.id});}}); document.querySelector('[data-delete]')?.addEventListener('click',async()=>{if(await confirmDialog({message:'Supprimer cette occasion ? Les idées seront seulement dissociées.',danger:true,confirmText:'Supprimer'})){await deleteOccasion(occasion.id);navigate('occasions');}}); }
function fields(o,people){ return `<div class="field"><label>Nom *</label><input name="name" value="${escapeHtml(o.name||'')}"></div><div class="field"><label>Type</label><select name="type">${options(OCCASION_TYPES,o.type||'autre')}</select></div><div class="field"><label>Date *</label><input type="date" name="date" value="${o.date||''}"></div><div class="field"><label>Personnes</label><select name="personIds" multiple>${peopleOptions(people)}</select></div><input name="totalBudget" type="number" min="0" placeholder="Budget global"><textarea name="notes" placeholder="Notes"></textarea>`; }
