import { setMain } from '../ui/dom.js';
import { listIdeas } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { listOccasions, getOccasion } from '../services/occasions.service.js';
import { panicResults, peopleWithoutIdeas } from '../services/panic.service.js';
import { getSettings } from '../services/settings.service.js';
import { ideaCard, empty } from '../ui/render.js';
import { navigate } from '../router.js';
import { bindIdeaCardActions } from '../ui/idea-card-actions.js';
import { escapeHtml, escapeAttr } from '../utils/strings.js';
export async function renderPanic(params={}){ const [ideas,people,occasions,settings]=await Promise.all([listIdeas(),listPeople(),listOccasions('toutes'),getSettings()]); const criteria={personId:params.personId||'',occasionId:params.occasionId||'',budgetMax:''}; const occ=criteria.occasionId?await getOccasion(criteria.occasionId):null; const compute=()=>{ criteria.personId=document.querySelector('#person').value; criteria.occasionId=document.querySelector('#occasion').value; criteria.budgetMax=document.querySelector('#budget').value; criteria.ignoreBudget=document.querySelector('#ignoreBudget').checked; criteria.includeNoOccasion=document.querySelector('#includeNoOccasion').checked; criteria.allPeople=document.querySelector('#allPeople').checked; const res=panicResults({ideas,people,criteria}); const occasion=occasions.find(o=>o.id===criteria.occasionId)||occ; const missing=peopleWithoutIdeas(occasion,ideas).map(pid=>people.find(p=>p.id===pid)?.name).filter(Boolean); document.querySelector('#panic-results').innerHTML=`${missing.length?`<div class="card"><b>⚠️ Personnes sans idée:</b> ${missing.map(escapeHtml).join(', ')}</div>`:''}<h2>Pépites détectées</h2>${res.best.length?res.best.map(x=>`<div class="card"><div class="panic-score">${x.score}</div>${ideaCard(x.idea,people,settings,{panic:true})}</div>`).join(''):empty('Aucune idée en zone sûre. Clique sur Élargir la recherche avant de courir au supermarché.')}<h2>Hors budget</h2>${res.outOfBudget.length?res.outOfBudget.map(x=>ideaCard(x.idea,people,settings,{panic:true})).join(''):empty('Aucune idée hors budget. Le portefeuille respire.')}`; bindCards(); }; setMain(`<section class="screen stack"><div class="hero"><h1>🚨 Mode Panique Cadeau</h1><p>Pas de ligne “pourquoi”. Juste les meilleures pistes, vite.</p></div><div class="card grid"><select id="person"><option value="">Toutes les personnes</option>${people.map(p=>`<option value="${escapeAttr(p.id)}" ${p.id===criteria.personId?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select><select id="occasion"><option value="">Toutes les occasions</option>${occasions.map(o=>`<option value="${escapeAttr(o.id)}" ${o.id===criteria.occasionId?'selected':''}>${escapeHtml(o.name)}</option>`).join('')}</select><input id="budget" type="number" placeholder="Budget max"><input id="delay" type="number" placeholder="Délai en jours"></div><details class="card"><summary>Élargir la recherche</summary><label><input id="ignoreBudget" type="checkbox"> ignorer budget</label><label><input id="includeNoOccasion" type="checkbox"> inclure idées sans occasion</label><label><input id="allPeople" type="checkbox"> élargir à toutes les personnes</label><p class="muted">Inclure toutes catégories est actif en V1.</p></details><div id="panic-results" class="stack"></div></section>`); ['person','occasion','budget','delay','ignoreBudget','includeNoOccasion','allPeople'].forEach(id=>document.querySelector('#'+id).oninput=compute); compute(); }
function bindCards(){ bindIdeaCardActions(document.querySelector('#panic-results'),{onStatusChanged:()=>renderPanic()}); }
