import { setMain } from '../ui/dom.js';
import { listIdeas } from '../services/ideas.service.js';
import { listPeople } from '../services/people.service.js';
import { getOccasion } from '../services/occasions.service.js';
import { panicResults, peopleWithoutIdeas } from '../services/panic.service.js';
import { getSettings } from '../services/settings.service.js';
import { ideaCard, empty } from '../ui/render.js';
import { bindIdeaCardActions } from '../ui/idea-card-actions.js';
import { escapeHtml, escapeAttr } from '../utils/strings.js';
export async function renderPanic(params={}){ const [ideas,people,settings,occ]=await Promise.all([listIdeas(),listPeople(),getSettings(),params.occasionId?getOccasion(params.occasionId):null]); const criteria={personId:params.personId||'',personIds:occ?.personIds||[],budgetMax:'',expandLevel:0}; const labels=['','Recherche élargie','Budget ignoré','Toutes les personnes incluses']; const compute=()=>{ criteria.personId=document.querySelector('#person').value; criteria.budgetMax=document.querySelector('#budget').value; criteria.includePriceless=criteria.expandLevel>=1; criteria.ignoreBudget=criteria.expandLevel>=2; criteria.allPeople=criteria.expandLevel>=3; const res=panicResults({ideas,people,criteria}); const missing=peopleWithoutIdeas(occ,ideas).map(pid=>people.find(p=>p.id===pid)?.name).filter(Boolean); document.querySelector('#expand-state').textContent=labels[criteria.expandLevel]; document.querySelector('#panic-results').innerHTML=`${occ?`<div class="card"><b>${escapeHtml(occ.name)}</b><p class="muted">Recherche sur les personnes concernées par cet événement.</p></div>`:''}${missing.length?`<div class="card"><b>⚠️ Personnes sans idée:</b> ${missing.map(escapeHtml).join(', ')}</div>`:''}<h2>Pistes cadeau</h2>${res.best.length?res.best.map(x=>ideaCard(x.idea,people,settings,{panic:true})).join(''):empty('Aucune idée en zone sûre. Clique sur Élargir la recherche avant de courir au supermarché.')}${res.outOfBudget.length?`<h2>Hors budget</h2>${res.outOfBudget.map(x=>ideaCard(x.idea,people,settings,{panic:true})).join('')}`:''}`; bindCards(); }; setMain(`<section class="screen stack"><div class="hero"><h1>🚨 Trouver un cadeau vite</h1><p>J’ai besoin d’un cadeau vite : une personne, un budget, et CadeauScope trie.</p></div><div class="card grid"><select id="person"><option value="">Pour qui ?</option>${people.map(p=>`<option value="${escapeAttr(p.id)}" ${p.id===criteria.personId?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select><input id="budget" type="number" placeholder="Budget max"></div><div class="card actions"><button class="btn ghost" id="expand">Élargir la recherche</button><span class="muted" id="expand-state"></span></div><div id="panic-results" class="stack"></div></section>`); ['person','budget'].forEach(id=>document.querySelector('#'+id).oninput=compute); document.querySelector('#expand').onclick=()=>{criteria.expandLevel=Math.min(criteria.expandLevel+1,3);compute();}; compute(); }
function bindCards(){ bindIdeaCardActions(document.querySelector('#panic-results'),{onStatusChanged:()=>{}}); }
