import { setMain } from '../ui/dom.js';
import { listPeople } from '../services/people.service.js';
import { listIdeas } from '../services/ideas.service.js';
import { listHistory } from '../services/history.service.js';
import { personCard, empty } from '../ui/render.js';
import { includesText } from '../utils/strings.js';
import { navigate } from '../router.js';
import { isIdeaActive } from '../models/ideas.model.js';
export async function renderPeople(){ const [people,ideas,history]=await Promise.all([listPeople(true),listIdeas(),listHistory()]); setMain(`<section class="screen stack"><div class="screen-header"><div><h1 class="screen-title">🧑‍🤝‍🧑 Personnes</h1><p class="screen-subtitle">Les proches, les indices, les tailles, les “surtout pas ça”.</p></div><button class="btn primary" data-new>Ajouter</button></div><input id="search" placeholder="Rechercher nom, relation, intérêts, marques, notes..."><div class="chip-row">${['Toutes','À préparer','Sans idée'].map((f,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><div id="people-list" class="list"></div></section>`); const render=()=>{ const f=document.querySelector('.chip.active').dataset.filter, q=document.querySelector('#search').value; let data=[...people]; if(f!=='Archivées') data=data.filter(p=>!p.archived); else data=data.filter(p=>p.archived); if(f==='À préparer') data=data.filter(p=>ideas.some(i=>i.personId===p.id&&isIdeaActive(i))); if(f==='Sans idée') data=data.filter(p=>!ideas.some(i=>i.personId===p.id&&isIdeaActive(i))); if(q)data=data.filter(p=>includesText(`${p.name} ${p.relation} ${p.interests} ${p.favoriteBrands} ${p.notes} ${p.avoid}`,q)); document.querySelector('#people-list').innerHTML=data.length?data.map(p=>personCard(p,ideas,history)).join(''):empty('Aucune personne trouvée. Même le radar a besoin d’un prénom.'); bindCards(); }; document.querySelector('[data-new]').onclick=()=>navigate('person',{id:'new'}); document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');render();}); document.querySelector('#search').oninput=render; render(); }
function bindCards(){ document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route,{id:b.dataset.id,personId:b.dataset.person})); }
