import { setMain, serializeForm } from '../ui/dom.js';
import { getPerson, savePerson, archivePerson, deletePerson } from '../services/people.service.js';
import { ideasForPerson } from '../services/ideas.service.js';
import { historyForPerson, saveHistory } from '../services/history.service.js';
import { RELATIONS, REACTIONS } from '../config.js';
import { options } from '../ui/forms.js';
import { ideaCard, empty } from '../ui/render.js';
import { bindIdeaCardActions } from '../ui/idea-card-actions.js';
import { escapeHtml, escapeAttr } from '../utils/strings.js';
import { formatBirthdayFr, formatDateFr } from '../utils/dates.js';
import { navigate } from '../router.js';
import { isIdeaActive } from '../models/ideas.model.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog, modal, closeModal } from '../ui/modals.js';
export async function renderPersonDetail({id}){ const isNew=id==='new'; const [person,ideas,history]=await Promise.all([isNew?null:getPerson(id),isNew?[]:ideasForPerson(id),isNew?[]:historyForPerson(id)]); if(isNew||!person){ setMain(`<section class="screen stack"><h1>Ajouter une personne</h1><form id="person-form" class="card form-card">${personFields({})}<button class="btn primary">Enregistrer</button></form></section>`); document.querySelector('#person-form').onsubmit=async e=>{e.preventDefault();try{const p=await savePerson(serializeForm(e.target));toast('Personne ajoutée. Nouvelle cible verrouillée.');navigate('person',{id:p.id});}catch(err){toast(Object.values(err.errors||{})[0]||err.message)}}; return; }
 setMain(`<section class="screen stack"><button class="btn" data-back>← Retour</button><article class="card"><h1>${escapeHtml(person.name)}</h1><div class="actions"><button class="btn primary" data-route="quick" data-person="${escapeAttr(person.id)}">Ajouter idée</button><button class="btn ghost" data-route="panic" data-person="${escapeAttr(person.id)}">Mode Panique</button><button class="btn" data-edit>Modifier personne</button><button class="btn danger" data-archive>${person.archived?'Restaurer':'Archiver'}</button><button class="btn danger" data-delete>Supprimer</button></div></article><h2>Infos</h2><div class="card details"><div class="detail-row"><b>Relation</b><span>${escapeHtml(RELATIONS[person.relation]||person.relation)}</span></div><div class="detail-row"><b>Anniversaire</b><span>${escapeHtml(person.birthday?formatBirthdayFr(person.birthday):'—')}</span></div></div><h2>Préférences</h2><div class="card"><p>👕 ${escapeHtml(person.clothingSize||'—')} · 👟 ${escapeHtml(person.shoeSize||'—')}</p><p><b>Intérêts:</b> ${escapeHtml(person.interests||'—')}</p><p><b>Couleurs:</b> ${escapeHtml(person.favoriteColors||'—')}</p><p><b>Marques:</b> ${escapeHtml(person.favoriteBrands||'—')}</p><p><b>À éviter:</b> ${escapeHtml(person.avoid||'—')}</p><p>${escapeHtml(person.notes||'')}</p></div><h2>Idées disponibles</h2>${ideas.filter(isIdeaActive).length?ideas.filter(isIdeaActive).map(i=>ideaCard(i,[person],{})).join(''):empty()}<h2>Historique</h2><div class="card"><button class="btn ghost" data-past>Ajouter un cadeau passé</button>${history.map(h=>`<p>🧾 ${escapeHtml(h.title)} · ${escapeHtml(formatDateFr(h.date))} · ${escapeHtml(REACTIONS[h.reaction]||'réaction non notée')}</p>`).join('')||'<p class="muted">Aucun cadeau passé. Le coffre est prêt.</p>'}</div></section>`); bind(person); }
function personFields(p){ return `<div class="field"><label>Nom *</label><input name="name" value="${escapeAttr(p.name||'')}" required></div><div class="field"><label>Relation</label><select name="relation">${options(RELATIONS,p.relation||'autre')}</select></div><div class="field"><label>Anniversaire</label><input name="birthday" placeholder="JJ-MM" inputmode="numeric" value="${escapeAttr(p.birthday?formatBirthdayFr(p.birthday):'')}"></div><textarea name="notes" placeholder="Notes">${escapeHtml(p.notes||'')}</textarea><details><summary>Préférences avancées</summary><div class="field"><label>Budget par défaut</label><input name="defaultBudget" type="number" min="0" step="0.01" value="${escapeAttr(p.defaultBudget ?? '')}"></div><div class="two grid"><input name="clothingSize" placeholder="Taille vêtements" value="${escapeAttr(p.clothingSize||'')}"><input name="shoeSize" placeholder="Pointure" value="${escapeAttr(p.shoeSize||'')}"></div><textarea name="interests" placeholder="Centres d’intérêt">${escapeHtml(p.interests||'')}</textarea><textarea name="favoriteColors" placeholder="Couleurs préférées">${escapeHtml(p.favoriteColors||'')}</textarea><textarea name="favoriteBrands" placeholder="Marques préférées">${escapeHtml(p.favoriteBrands||'')}</textarea><textarea name="avoid" placeholder="À éviter">${escapeHtml(p.avoid||'')}</textarea></details>`; }
function bind(person){ bindIdeaCardActions(document); document.querySelector('[data-back]').onclick=()=>navigate('people'); document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route,{id:b.dataset.id,personId:b.dataset.person})); document.querySelector('[data-archive]').onclick=async()=>{await archivePerson(person.id,!person.archived);navigate('person',{id:person.id});}; document.querySelector('[data-delete]').onclick=async()=>{try{if(await confirmDialog({message:'Supprimer définitivement cette personne ?',danger:true,confirmText:'Supprimer'})){await deletePerson(person.id);navigate('people');}}catch(e){toast(e.message)}}; document.querySelector('[data-edit]').onclick=()=>modal({title:'Modifier personne',body:`<form id="edit-person" class="form-card">${personFields(person)}<button class="btn primary">Enregistrer</button></form>`}); document.querySelector('[data-past]').onclick=()=>modal({title:'Ajouter un cadeau passé',body:`<form id="past" class="form-card"><input name="title" placeholder="Cadeau" required><input name="price" type="number" step="0.01" placeholder="Prix"><input name="date" type="text" inputmode="numeric" placeholder="JJ-MM-AAAA"><select name="reaction"><option value="">Réaction</option>${options(REACTIONS)}</select><textarea name="note" placeholder="Note"></textarea><button class="btn primary">Ajouter</button></form>`}); document.addEventListener('submit',async e=>{ if(e.target.id==='edit-person'){e.preventDefault(); await savePerson({...person,...serializeForm(e.target)}); toast('Personne mise à jour.'); closeModal(); navigate('person',{id:person.id});} if(e.target.id==='past'){e.preventDefault(); await saveHistory({...serializeForm(e.target),personId:person.id}); toast('Cadeau passé ajouté. Le coffre se remplit.'); closeModal(); navigate('person',{id:person.id});} },{once:true}); }
