import { setMain, serializeForm } from '../ui/dom.js';
import { navigate } from '../router.js';
import { listPeople, savePerson } from '../services/people.service.js';
import { activeCategories } from '../services/categories.service.js';
import { saveIdea } from '../services/ideas.service.js';
import { savePhoto } from '../services/photos.service.js';
import { getSettings } from '../services/settings.service.js';
import { getOccasion } from '../services/occasions.service.js';
import { peopleOptions, categoryOptions, INTEREST_LEVELS, options } from '../ui/forms.js';
import { toast } from '../ui/toasts.js';
import { safeHttpUrl } from '../utils/strings.js';
export async function renderQuickCapture(params={}){ const [people,cats,settings,initialOcc]=await Promise.all([listPeople(),activeCategories(),getSettings(),params.occasionId?getOccasion(params.occasionId):null]); const prefilledPerson=params.personId||((initialOcc?.personIds||[]).length===1?initialOcc.personIds[0]:''); setMain(`<section class="screen stack"><div class="screen-header"><div><h1 class="screen-title">➕ Nouvelle idée</h1><p class="screen-subtitle">Une personne, une idée, et c’est noté.</p></div></div>${!people.length?`<div class="card"><p>Aucune personne. CadeauScope a besoin d’une cible consentante.</p><form id="mini-person" class="actions"><input name="name" placeholder="Nom" required><button class="btn primary">Créer</button></form></div>`:''}<form id="idea-form" class="card form-card"><div class="field"><label>Pour qui ? *</label><select name="personId" required><option value="">Choisir</option>${peopleOptions(people,prefilledPerson)}</select></div><div class="field"><label>Idée cadeau *</label><input name="title" required placeholder="Ex : couteau japonais, casque, chaussettes de compétition"></div><div class="field"><label>Prix approx.</label><input name="estimatedPrice" type="number" min="0" step="0.01" placeholder="ex : 30"></div><div class="field"><label>Note ou lien</label><textarea name="noteOrLink" placeholder="Une note courte ou https://..."></textarea></div><details><summary>Détails optionnels</summary><div class="stack"><div class="field"><label>Description</label><textarea name="description"></textarea></div><div class="field"><label>Catégorie</label><select name="categoryId">${categoryOptions(cats,settings.defaultCategoryId)}</select></div><div class="field"><label>Niveau d’intérêt</label><select name="interestLevel">${options(INTEREST_LEVELS,settings.defaultInterestLevel)}</select></div><div class="field"><label>Photo</label><input name="photo" type="file" accept="image/*"><small class="muted">Stockage local IndexedDB si ajoutée. Aucune photo fournie par le projet.</small></div></div></details><div class="actions"><button class="btn primary" name="mode" value="save">Enregistrer</button><button class="btn ghost" name="mode" value="again">Enregistrer + nouvelle idée</button><button class="btn" type="button" data-cancel>Annuler</button></div></form></section>`); bind(params); }
function splitNoteOrLink(data){ const noteOrLink=String(data.noteOrLink||'').trim(); delete data.noteOrLink; data.status='idee'; data.occasionMode='none'; data.occasionId=''; data.priceText=''; if(noteOrLink){ const url=safeHttpUrl(noteOrLink); if(url && url===noteOrLink) data.link=url; else data.note=noteOrLink; } return data; }
async function attachPhoto(idea, file){ if(!file) return idea; const photo=await savePhoto({ownerType:'idea',ownerId:idea.id,blob:file,mimeType:file.type}); return saveIdea({...idea,photoId:photo.id}); }
function bind(params){ document.querySelector('[data-cancel]').onclick=()=>navigate('home'); document.querySelector('#mini-person')?.addEventListener('submit',async e=>{e.preventDefault(); await savePerson(serializeForm(e.target)); toast('Personne ajoutée. Le radar a une nouvelle cible.'); renderQuickCapture(params);}); document.querySelector('#idea-form').addEventListener('submit',async e=>{ e.preventDefault(); const submit=e.submitter?.value; try{ const form=e.target; const file=form.photo.files[0]; const data=splitNoteOrLink(serializeForm(form)); let idea=await saveIdea(data); idea=await attachPhoto(idea,file); toast('Idée capturée. Ruban mental posé.'); if(submit==='again') renderQuickCapture({personId:data.personId}); else navigate('ideas'); }catch(err){ toast(Object.values(err.errors||{})[0]||err.message); } }); }
