import { setMain, serializeForm } from '../ui/dom.js';
import { navigate } from '../router.js';
import { listPeople, savePerson } from '../services/people.service.js';
import { activeCategories } from '../services/categories.service.js';
import { saveIdea } from '../services/ideas.service.js';
import { getSettings } from '../services/settings.service.js';
import { options, peopleOptions, categoryOptions, STATUSES, INTEREST_LEVELS } from '../ui/forms.js';
import { toast } from '../ui/toasts.js';
export async function renderQuickCapture(params={}){ const [people,cats,settings]=await Promise.all([listPeople(),activeCategories(),getSettings()]); setMain(`<section class="screen stack"><div class="screen-header"><div><h1 class="screen-title">➕ Capture rapide</h1><p class="screen-subtitle">Objectif: moins de 10 secondes, chrono mental inclus.</p></div></div>${!people.length?`<div class="card"><p>Aucune personne. CadeauScope a besoin d’une cible consentante.</p><form id="mini-person" class="actions"><input name="name" placeholder="Nom" required><button class="btn primary">Créer</button></form></div>`:''}<form id="idea-form" class="card form-card"><div class="field"><label>Pour qui ? *</label><select name="personId" required><option value="">Choisir</option>${peopleOptions(people,params.personId)}</select></div><div class="field"><label>Idée cadeau *</label><input name="title" required placeholder="Ex: couteau japonais, casque, chaussettes de compétition"></div><div class="two grid"><div class="field"><label>Prix estimé</label><input name="estimatedPrice" type="number" min="0" step="0.01"></div><div class="field"><label>Budget approximatif</label><input name="priceText" placeholder="30-50 €"></div></div><div class="field"><label>Note</label><textarea name="note"></textarea></div><div class="field"><label>Occasion</label><select name="occasionMode"><option value="none">Aucune</option><option value="birthday">Anniversaire</option><option value="christmas">Noël</option><option value="manual">Manuelle</option></select></div><div class="field"><label>Niveau d’intérêt</label><select name="interestLevel">${options(INTEREST_LEVELS,settings.defaultInterestLevel)}</select></div><details><summary>Options avancées</summary><div class="stack"><div class="field"><label>Description</label><textarea name="description"></textarea></div><div class="field"><label>Lien web</label><input name="link" placeholder="https://..."></div><div class="field"><label>Catégorie</label><select name="categoryId">${categoryOptions(cats,settings.defaultCategoryId)}</select></div><div class="field"><label>Photo</label><input name="photo" type="file" accept="image/*"><small class="muted">Stockage local IndexedDB si ajoutée. Aucune photo fournie par le projet.</small></div><div class="field"><label>Statut</label><select name="status">${options(STATUSES,settings.defaultIdeaStatus)}</select></div></div></details><div class="actions"><button class="btn primary" name="mode" value="save">Enregistrer</button><button class="btn ghost" name="mode" value="again">Enregistrer + nouvelle idée</button><button class="btn" type="button" data-cancel>Annuler</button></div></form></section>`); bind(params); }
function bind(params){ document.querySelector('[data-cancel]').onclick=()=>navigate('home'); document.querySelector('#mini-person')?.addEventListener('submit',async e=>{e.preventDefault(); await savePerson(serializeForm(e.target)); toast('Personne ajoutée. Le radar a une nouvelle cible.'); renderQuickCapture(params);}); document.querySelector('#idea-form').addEventListener('submit',async e=>{ e.preventDefault(); const submit=e.submitter?.value; try{ const data=serializeForm(e.target); await saveIdea(data); toast('Idée capturée. Ruban mental posé.'); if(submit==='again') renderQuickCapture({personId:data.personId}); else navigate('ideas'); }catch(err){ toast(Object.values(err.errors||{})[0]||err.message); } }); }
