import { setMain } from '../ui/dom.js';
import { getSettings, saveSettings } from '../services/settings.service.js';
import { exportJson, importJson } from '../services/import-export.service.js';
import { readJsonFile } from '../utils/files.js';
import { toast } from '../ui/toasts.js';
import { confirmDialog } from '../ui/modals.js';
import { clearDb } from '../db/db.js';
import { seedDefaults } from '../db/seed.js';
import { APP } from '../config.js';
export async function renderSettings(){ const s=await getSettings(); setMain(`<section class="screen stack"><div class="screen-header"><div><h1 class="screen-title">⚙️ Réglages</h1><p class="screen-subtitle">Le poste de contrôle du traîneau.</p></div></div><form id="settings-form" class="card settings-section"><h2>Apparence</h2><label><input type="radio" name="theme" value="auto" ${s.theme==='auto'?'checked':''}> Thème automatique</label><label><input type="radio" name="theme" value="light" ${s.theme==='light'?'checked':''}> Thème clair</label><label><input type="radio" name="theme" value="dark" ${s.theme==='dark'?'checked':''}> Thème sombre</label><h2>Préférences cadeaux</h2><input name="currency" value="${s.currency}" placeholder="Devise"><input name="eventWarningDays" type="number" value="${s.eventWarningDays}"><input name="christmasWarningDays" type="number" value="${s.christmasWarningDays}"><button class="btn primary">Enregistrer</button></form><section class="card settings-section"><h2>Sauvegarde</h2><button class="btn ghost" id="export">Exporter JSON</button><label class="btn">Importer JSON<input id="import" type="file" accept="application/json" hidden></label><p class="muted">Les photos sont exclues de l’export V1.</p></section><section class="card settings-section danger-zone"><h2>Données avancées</h2><p>Voir personnes/occasions archivées via leurs filtres dédiés. Gérer catégories personnalisées: V1 prête côté données.</p><button class="btn danger" id="reset">Réinitialiser l’application</button></section><section class="card"><h2>À propos</h2><p>${APP.name} ${APP.version}</p><p>Pas de compte, pas de cloud, pas de pub. Juste ton coffre local à idées.</p></section></section>`); document.querySelector('#settings-form').onsubmit=async e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target).entries()); await saveSettings(d); toast('Réglages enregistrés. Radar recalibré.');}; document.querySelector('#export').onclick=async()=>{await exportJson(); toast('Sauvegarde prête. Ton coffre à idées est dans le fichier.');}; document.querySelector('#import').onchange=async e=>{ const file=e.target.files[0]; if(!file)return; if(await confirmDialog({message:'Attention, l’import remplacera toutes les données actuelles. Pense à exporter une sauvegarde avant de continuer.',danger:true,confirmText:'Importer'})){ await importJson(await readJsonFile(file)); toast('Import terminé. Le coffre est rechargé.'); } }; document.querySelector('#reset').onclick=async()=>{ const value=prompt('Dernier contrôle avant effacement total du traîneau. Saisis exactement SUPPRIMER.'); if(value==='SUPPRIMER'){ await clearDb(); await seedDefaults(); toast('Application réinitialisée. Neige fraîche.'); location.reload(); } }; }
