import { STATUSES, LEGACY_STATUSES } from '../config.js';
import { normalizeIdeaStatus } from '../models/ideas.model.js';
import { isValidOptionalNumber } from '../utils/numbers.js';
import { normalizeLegacyDate, normalizeLegacyBirthday } from '../utils/dates.js';
export function validateIdea(data){ const errors={}; if(!data.personId) errors.personId='Choisis une personne: CadeauScope ne lit pas encore dans les pensées.'; if(!String(data.title||'').trim()) errors.title='Note au moins le titre de l’idée.'; if(!isValidOptionalNumber(data.estimatedPrice,{min:0})) errors.estimatedPrice='Prix estimé positif ou vide.'; if(data.link && !/^https?:\/\//i.test(String(data.link).trim())) errors.link='Le lien doit commencer par http:// ou https://'; if(data.status && !STATUSES[normalizeIdeaStatus(data.status)] && !LEGACY_STATUSES[data.status]) errors.status='Statut inconnu.'; const level=Number(data.interestLevel||2); if(!Number.isFinite(level)||level<1 || level>4) errors.interestLevel='Niveau entre 1 et 4.'; return errors; }
export function validatePerson(data){ const errors={}; if(!String(data.name||'').trim()) errors.name='Nom obligatoire. Même “Tonton mystère” marche.'; if(data.birthday && !normalizeLegacyBirthday(data.birthday)) errors.birthday='Anniversaire attendu au format JJ-MM.'; if(!isValidOptionalNumber(data.defaultBudget,{min:0})) errors.defaultBudget='Budget personne positif ou vide.'; return errors; }
export function validateOccasion(data){ const errors={}; if(!String(data.name||'').trim()) errors.name='Nom obligatoire.'; if(!data.date) errors.date='Date obligatoire.'; else if(!normalizeLegacyDate(data.date)) errors.date='Date attendue au format JJ-MM-AAAA.'; if(!isValidOptionalNumber(data.totalBudget,{min:0})) errors.totalBudget='Budget positif ou vide.'; return errors; }
export function validateSettings(data){ const errors={}; if(!isValidOptionalNumber(data.eventWarningDays,{positive:true})) errors.eventWarningDays='Délai événements: nombre de jours supérieur à 0.'; if(!isValidOptionalNumber(data.christmasWarningDays,{positive:true})) errors.christmasWarningDays='Délai Noël: nombre de jours supérieur à 0.'; return errors; }
export function validateHistory(data){ const errors={}; if(data.date && !normalizeLegacyDate(data.date)) errors.date='Date attendue au format JJ-MM-AAAA.'; if(!isValidOptionalNumber(data.price,{min:0})) errors.price='Prix historique positif ou vide.'; return errors; }
export const hasErrors = errors => Object.keys(errors).length > 0;
